version: '3.8'

services:
  vllm_server:
    image: docker.io/vllm/vllm-openai:latest
    container_name: vllm_server
    ports:
      - "8000:8000"
    volumes:
      - ~/.cache/huggingface:/root/.cache/huggingface
    environment:
      - HUGGING_FACE_HUB_TOKEN=${HF_TOKEN}
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    shm_size: 8g
    command: >
      --model Qwen/Qwen3-0.6B
      --max-model-len 8192
      --gpu-memory-utilization 0.5
      --max-num-seqs 2
      --enable-auto-tool-choice
      --tool-call-parser hermes
    restart: unless-stopped




      #--model TheBloke/Mistral-7B-Instruct-v0.2-AWQ
#--max-model-len 8192
#--quantization awq